Traceback (most recent call last):
  File "/home/aih/sebastian.birk/workspace/projects/nichecompass-reproducibility/scripts/sample_integration_method_benchmarking/../compute_benchmarking_metrics.py", line 124, in <module>
    benchmark_dict = compute_benchmarking_metrics(
  File "/home/aih/sebastian.birk/workspace/projects/nichecompass/nichecompass/benchmarking/metrics.py", line 322, in compute_benchmarking_metrics
    X=adata.obsp[f"{latent_key}_50knng_distances"],
  File "/home/aih/sebastian.birk/miniconda3/envs/nichecompass-test/lib/python3.9/site-packages/anndata/_core/aligned_mapping.py", line 178, in __getitem__
    return self._data[key]
KeyError: 'nichecompass_latent_run1_50knng_distances'
